### DISCUSSION TITLE
Ultimate UI goal: Scenarios that do everything without a graph file

### DISCUSSION THREAD

**Discussion by pinheadmz** [bitcoin-dev-project/warnet#364] [Ideas]
Most experiments with Warnet require at least one graphml file and one scenario. Graphml is a fairly annoying format and is likely to be overkill:

- it requires pre-defining all data tag "keys" at the top of the file
- we need to use tools to generate large graphs
- lightning channels and layer 1 p2p connections both use graphml `edge`'s and the difference is subtle

SO WHAT IF...

- We restructure warnet more like a library
- Break out all the functions in scenarios like `ln_init.py` and eventually [`onion_init.py`](https://github.com/bitcoin-dev-project/warnet/blob/97965bf0afd3e6327609cb2440f74056a0f870fc/src/scenarios/onion_init.py) so they can be imported into new scenarios as library functions
- Add methods to generate graphs with a more robust format:
    - "i need 100 nodes, each with lnd and *this* circuitbreaker image" could be one single command, etc

ALSO...

There are tons of functions in the bitcoin test framework we cant support without stubbing (i.e. `assert_debug_log()`) and we do not need proxies-on-proxies for, like, code coverage. That's why I think we should plan long term on dropping the bitcoin test framework and writing our own.

HELL...

These single-point-of-entry scenario files could even launch kubernetes locally or ensure its already running or whatever. Then we can also remove all the justfile commands and integrate everything into one place.

Imagine:
"How do I use Warnet?"
"You write one file, and execute one command"

**Comment by josibake** [comment]
Agree with this direction longterm. I think we are outgrowing the initial idea of "everyone is going to use the bitcoin test framework" and have learned instead that usually there is a lot of setup required to get something working, e.g. opening lightning channels, mining a chain so wallets have UTXOs, etc.

The library approach makes a lot of sense to me in that you can pull stuff in as needed and then flexibility to write code for what you want to happen.

> HELL...
>
> These single-point-of-entry scenario files could even launch kubernetes locally or ensure its already running or whatever. Then we > can also remove all the justfile commands and integrate everything into one place.

This is the north star, imo. We can also dogfood any of the code we are exposing in a "library" by building the CLI directly on top of it, i.e. the CLI is a client of the library code we are writing.

**Comment by willcl-ark** [comment]
I mean, also concept ACK on this.

I'd just not that this was the intention of the `graph generate` command originally. It had capability to do `n` nodes, connected using any `networkx`-supported graph type, and could use random bitcoin core versions. It could in theory be reverted to behave like this, in addition to suporting LND and circuitbreaker stuff?

IMO I think one mistake we have arguably made is going _too_ genric over everything. Perhaps we should define warnet as:

- Makes a network of `n` nodes
	- where `m` of those can optionally have associated LND/Core Lightning nodes
	- where `p` of those can optionally have associated circuitbreaker nodes
- Connected in **this specific topology** by default
- etc.

Perhaps the easiest way to do this using some "kind of" DSL as was previously discussed, would be with a config yaml/toml which warnet parses?

```toml
# Network Configuration Schema

[network]
# Number of total nodes in the network
n = 10

# Number of nodes with associated LND/Core Lightning nodes
m = 5

# Number of nodes with associated Circuitbreaker nodes
p = 3

# Specify the topology
topology = "erdos-renyi"

# Docker images for each node type
[docker_images]
# Docker image for regular nodes
regular = "node:latest"

# Docker image for nodes with LND/Core Lightning
lightning = "lnd:latest"

# Docker image for nodes with Circuitbreaker
circuitbreaker = "circuitbreaker:latest"

# Bitcoind node options
[bitcoind_options]
debug = 1
blocksonly = 1

```

At this point, it may not even be particularly worth bothering to parse this all into graphml. Just use `networkx` to generate a `topology`-type graph with the required nodes and edges, then use that mapping to make connections...
